In [1]:
import numpy as np

In [28]:
a = np.array([ [[[3,2],[3,2]],[3,2],[3,2]],[[[3,2],[3,2]],[3,2],[3,2]],[[[3,2],[3,2]],[3,2],[3,2]] ])
print(a.shape)

(3, 3, 2)


In [29]:
b = a.reshape(a.shape[0],-1)
print(b.shape)

(3, 6)


In [41]:
def convert_to_one_hot(Y, C):
    Y = np.eye(C)[Y.reshape(-1)].T
    return Y

In [42]:
y = np.array([1,2,3,4])
convert_to_one_hot(y,5)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [38]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [40]:
np.eye(5)[[1,2,3]]

array([[ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])